/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Appointment = IDL.Record({
  'id' : IDL.Text,
  'doctorId' : IDL.Principal,
  'patientId' : IDL.Text,
  'time' : Time,
  'reason' : IDL.Text,
});
export const ConsultationSession = IDL.Record({
  'id' : IDL.Text,
  'prescription' : IDL.Opt(IDL.Text),
  'notes' : IDL.Text,
  'appointmentId' : IDL.Text,
  'followUpDate' : IDL.Opt(Time),
});
export const Patient = IDL.Record({
  'id' : IDL.Text,
  'age' : IDL.Nat,
  'name' : IDL.Text,
  'medicalHistory' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAppointment' : IDL.Func([Appointment], [], []),
  'createConsultationSession' : IDL.Func([ConsultationSession], [], []),
  'createPatient' : IDL.Func([Patient], [], []),
  'deleteAppointment' : IDL.Func([IDL.Text], [], []),
  'deleteConsultationSession' : IDL.Func([IDL.Text], [], []),
  'deletePatient' : IDL.Func([IDL.Text], [], []),
  'getAllAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
  'getAllConsultationSessions' : IDL.Func(
      [],
      [IDL.Vec(ConsultationSession)],
      ['query'],
    ),
  'getAllPatients' : IDL.Func([], [IDL.Vec(Patient)], ['query']),
  'getAppointment' : IDL.Func([IDL.Text], [IDL.Opt(Appointment)], ['query']),
  'getAppointmentsByPatient' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Appointment)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConsultationSession' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ConsultationSession)],
      ['query'],
    ),
  'getConsultationsByAppointment' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ConsultationSession)],
      ['query'],
    ),
  'getPatient' : IDL.Func([IDL.Text], [IDL.Opt(Patient)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateAppointment' : IDL.Func([IDL.Text, Appointment], [], []),
  'updateConsultationSession' : IDL.Func(
      [IDL.Text, ConsultationSession],
      [],
      [],
    ),
  'updatePatient' : IDL.Func([IDL.Text, Patient], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Appointment = IDL.Record({
    'id' : IDL.Text,
    'doctorId' : IDL.Principal,
    'patientId' : IDL.Text,
    'time' : Time,
    'reason' : IDL.Text,
  });
  const ConsultationSession = IDL.Record({
    'id' : IDL.Text,
    'prescription' : IDL.Opt(IDL.Text),
    'notes' : IDL.Text,
    'appointmentId' : IDL.Text,
    'followUpDate' : IDL.Opt(Time),
  });
  const Patient = IDL.Record({
    'id' : IDL.Text,
    'age' : IDL.Nat,
    'name' : IDL.Text,
    'medicalHistory' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAppointment' : IDL.Func([Appointment], [], []),
    'createConsultationSession' : IDL.Func([ConsultationSession], [], []),
    'createPatient' : IDL.Func([Patient], [], []),
    'deleteAppointment' : IDL.Func([IDL.Text], [], []),
    'deleteConsultationSession' : IDL.Func([IDL.Text], [], []),
    'deletePatient' : IDL.Func([IDL.Text], [], []),
    'getAllAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
    'getAllConsultationSessions' : IDL.Func(
        [],
        [IDL.Vec(ConsultationSession)],
        ['query'],
      ),
    'getAllPatients' : IDL.Func([], [IDL.Vec(Patient)], ['query']),
    'getAppointment' : IDL.Func([IDL.Text], [IDL.Opt(Appointment)], ['query']),
    'getAppointmentsByPatient' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Appointment)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConsultationSession' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ConsultationSession)],
        ['query'],
      ),
    'getConsultationsByAppointment' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ConsultationSession)],
        ['query'],
      ),
    'getPatient' : IDL.Func([IDL.Text], [IDL.Opt(Patient)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateAppointment' : IDL.Func([IDL.Text, Appointment], [], []),
    'updateConsultationSession' : IDL.Func(
        [IDL.Text, ConsultationSession],
        [],
        [],
      ),
    'updatePatient' : IDL.Func([IDL.Text, Patient], [], []),
  });
};

export const init = ({ IDL }) => { return []; };