/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Appointment {
  'id' : string,
  'doctorId' : Principal,
  'patientId' : string,
  'time' : Time,
  'reason' : string,
}
export interface ConsultationSession {
  'id' : string,
  'prescription' : [] | [string],
  'notes' : string,
  'appointmentId' : string,
  'followUpDate' : [] | [Time],
}
export interface Patient {
  'id' : string,
  'age' : bigint,
  'name' : string,
  'medicalHistory' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAppointment' : ActorMethod<[Appointment], undefined>,
  'createConsultationSession' : ActorMethod<[ConsultationSession], undefined>,
  'createPatient' : ActorMethod<[Patient], undefined>,
  'deleteAppointment' : ActorMethod<[string], undefined>,
  'deleteConsultationSession' : ActorMethod<[string], undefined>,
  'deletePatient' : ActorMethod<[string], undefined>,
  'getAllAppointments' : ActorMethod<[], Array<Appointment>>,
  'getAllConsultationSessions' : ActorMethod<[], Array<ConsultationSession>>,
  'getAllPatients' : ActorMethod<[], Array<Patient>>,
  'getAppointment' : ActorMethod<[string], [] | [Appointment]>,
  'getAppointmentsByPatient' : ActorMethod<[string], Array<Appointment>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConsultationSession' : ActorMethod<[string], [] | [ConsultationSession]>,
  'getConsultationsByAppointment' : ActorMethod<
    [string],
    Array<ConsultationSession>
  >,
  'getPatient' : ActorMethod<[string], [] | [Patient]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateAppointment' : ActorMethod<[string, Appointment], undefined>,
  'updateConsultationSession' : ActorMethod<
    [string, ConsultationSession],
    undefined
  >,
  'updatePatient' : ActorMethod<[string, Patient], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];